export const childProfileSeed = {
  slug: 'alex-early-primary',
  childName: 'Alex',
  parentEmail: 'parent@example.com',
  ageBand: 'Early Primary',
  preferredModality: 'visual',
  interests: ['music', 'stories', 'puzzles'],
  goals: ['phonics', 'counting', 'confidence'],
  confidence: 0.4,
};

export const subjectSeeds = [
  {
    id: 'speech',
    name: 'Speech & Therapy',
    emoji: '🗣️',
    accent: '#8b5cf6',
    shadow: 'rgba(139, 92, 246, 0.35)',
    textStroke: '#5b21b6',
    mascotPrompt: "Let's make some magic sounds!",
    games: [
      {
        id: 'speech-playground',
        title: 'Speech Magic',
        description: 'Use your voice to cast magic spells and move obstacles!',
        status: 'ready',
        route: '/speech-therapy',
      },
    ],
  },
  {
    id: 'english',
    name: 'English',
    emoji: '📖',
    accent: '#ff7a45',
    shadow: 'rgba(255, 122, 69, 0.34)',
    textStroke: '#ef5a29',
    mascotPrompt: 'Story time!',
    games: [
      {
        id: 'match-letters',
        title: 'Match Letters',
        description: 'Drag uppercase and lowercase balloons together.',
        route: '/english-match-letters',
        status: 'ready',
      },
      {
        id: 'draw-letters',
        title: 'Draw Letters',
        description: 'Trace giant letters with your hand.',
        status: 'coming-soon',
      },
      {
        id: 'guess-word',
        title: 'Guess the Word',
        description: 'Look at the picture and drag letters to spell the word!',
        status: 'ready',
        route: '/english-guess-word',
      },
    ],
  },
  {
    id: 'maths',
    name: 'Maths',
    emoji: '🔢',
    accent: '#8b5cf6',
    shadow: 'rgba(139, 92, 246, 0.35)',
    textStroke: '#6d28d9',
    mascotPrompt: 'Number power!',
    games: [
      {
        id: 'count-fingers',
        title: 'Count Fingers',
        description: 'Count and match with your hands.',
        status: 'coming-soon',
      },
      {
        id: 'build-equation',
        title: 'Build the Equation',
        description: 'Drag numbers and symbols to build a correct math problem!',
        status: 'ready',
        route: '/math-equations',
      },
      {
        id: 'football-math',
        title: 'Football Math',
        description: 'Solve math equations to score epic goals!',
        status: 'ready',
        externalUrl: 'https://game-five-flax.vercel.app/',
      },
    ],
  },
  {
    id: 'science',
    name: 'Science',
    emoji: '🔬',
    accent: '#22c55e',
    shadow: 'rgba(34, 197, 94, 0.35)',
    textStroke: '#15803d',
    mascotPrompt: 'Blast into space!',
    games: [
      {
        id: 'color-match',
        title: 'Solar System Adventure',
        description: 'Jump straight into the live solar system game.',
        route: '/science-solar',
        status: 'ready',
      },
    ],
  },
  {
    id: 'social-science',
    name: 'Social Science',
    emoji: '🌍',
    accent: '#06b6d4',
    shadow: 'rgba(6, 182, 212, 0.35)',
    textStroke: '#0f766e',
    mascotPrompt: 'Let us explore the world!',
    games: [
      {
        id: 'basic-quiz',
        title: 'Basic Quiz',
        description: 'Travel the world with easy prompts.',
        status: 'coming-soon',
      },
    ],
  },
  {
    id: 'exercise',
    name: 'Exercise Games',
    emoji: '🏃‍♂️',
    accent: '#fb923c',
    shadow: 'rgba(251, 146, 60, 0.35)',
    textStroke: '#9a3412',
    mascotPrompt: 'Time to move your body!',
    games: [
      {
        id: 'fitness-adventure',
        title: 'Fitness Adventure',
        description: 'Jump, duck, and move to play the game!',
        status: 'ready',
        externalUrl: 'https://exercisesfinal.vercel.app/',
      },
    ],
  },
  {
    id: 'sign-language',
    name: 'Sign Language',
    emoji: '👐',
    accent: '#38bdf8',
    shadow: 'rgba(56, 189, 248, 0.35)',
    textStroke: '#0284c7',
    mascotPrompt: 'Watch my hands!',
    games: [
      {
        id: 'path-of-lumina',
        title: 'Path of Lumina',
        description: 'Use your hands to bring light back to the world!',
        status: 'ready',
        route: '/deaf-lumina',
      },
      {
        id: 'deaf-practice',
        title: 'Deaf Practice Hub',
        description: 'Advanced sign language practices and games!',
        status: 'ready',
        externalUrl: 'https://playguugle-deaf.vercel.app/',
      },
    ],
  },
] as const;

export const wordChallengeSeeds = [
  { id: '1', word: 'APPLE', hint: 'A sweet, crunchy fruit!', imageEmoji: '🍎', order: 1 },
  { id: '2', word: 'BALL', hint: 'You bounce and throw it!', imageEmoji: '⚽', order: 2 },
  { id: '3', word: 'SUN', hint: 'Hot and bright in the sky!', imageEmoji: '☀️', order: 3 },
  { id: '4', word: 'CAT', hint: 'Says meow!', imageEmoji: '🐱', order: 4 },
  { id: '5', word: 'TREE', hint: 'Tall with green leaves!', imageEmoji: '🌳', order: 5 },
] as const;

export const mathEquationSeeds = [
  { key: 'easy-1', level: 'easy', elements: ['2', '+', '3', '=', '5'], order: 1 },
  { key: 'easy-2', level: 'easy', elements: ['4', '−', '1', '=', '3'], order: 2 },
  { key: 'easy-3', level: 'easy', elements: ['1', '+', '1', '=', '2'], order: 3 },
  { key: 'medium-1', level: 'medium', elements: ['5', '×', '2', '=', '10'], order: 4 },
  { key: 'medium-2', level: 'medium', elements: ['8', '÷', '2', '=', '4'], order: 5 },
  { key: 'medium-3', level: 'medium', elements: ['10', '−', '4', '=', '6'], order: 6 },
  { key: 'hard-1', level: 'hard', elements: ['4', '×', '2', '+', '1', '=', '9'], order: 7 },
  { key: 'hard-2', level: 'hard', elements: ['10', '÷', '2', '+', '3', '=', '8'], order: 8 },
  { key: 'hard-3', level: 'hard', elements: ['5', '+', '5', '−', '2', '=', '8'], order: 9 },
] as const;

export const speechLevelSeeds = [
  {
    id: 'lvl-1',
    title: 'Roar like a Dragon',
    type: 'word',
    targetWord: 'roar',
    slowPronunciation: 'Rrrrrooooaaarrrr',
    instruction: 'Tell the dragon to move! Say "ROAR"',
    mascotIntro: 'The dragon is blocking the path! Tell him to ROAR!',
    mascotSuccess: 'The dragon moved! Great R sound!',
    emoji: '🐉',
  },
  {
    id: 'lvl-2',
    title: 'Call the Lion',
    type: 'word',
    targetWord: 'lion',
    slowPronunciation: 'Lllliiiiiiooonnn',
    instruction: 'Call our friend! Say "LION"',
    mascotIntro: 'Can you call the Lion? Practice your L sound!',
    mascotSuccess: 'He heard you! Perfect!',
    emoji: '🦁',
  },
  {
    id: 'lvl-3',
    title: 'Wake the Rabbit',
    type: 'word',
    targetWord: 'rabbit',
    slowPronunciation: 'Rrrrrraaabbbiiittt',
    instruction: 'Wake up the bunny! Say "RABBIT"',
    mascotIntro: 'The bunny is sleeping! Say Rabbit to wake him!',
    mascotSuccess: 'Hop hop! You did it!',
    emoji: '🐇',
  },
  {
    id: 'lvl-4',
    title: 'Pick an Apple',
    type: 'word',
    targetWord: 'apple',
    slowPronunciation: 'Aaaappppllle',
    instruction: 'Reach for the fruit! Say "APPLE"',
    mascotIntro: 'I am hungry! Can you say Apple?',
    mascotSuccess: 'Yummy! Great job!',
    emoji: '🍎',
  },
  {
    id: 'lvl-5',
    title: 'Hiss like a Snake',
    type: 'word',
    targetWord: 'snake',
    slowPronunciation: 'Sssssnnnnnaaaakkke',
    instruction: 'Talk to the reptile! Say "SNAKE"',
    mascotIntro: 'Watch out for the tall grass! Say Snake!',
    mascotSuccess: 'Sssss-uperb! You got it!',
    emoji: '🐍',
  },
  {
    id: 'lvl-6',
    title: 'Greet the Turtle',
    type: 'word',
    targetWord: 'turtle',
    slowPronunciation: 'Ttttuuurrrttllle',
    instruction: 'Say hello! Say "TURTLE"',
    mascotIntro: 'He moves so slow! Let us say Turtle!',
    mascotSuccess: 'He popped out of his shell! Nice T sound!',
    emoji: '🐢',
  },
  {
    id: 'lvl-7',
    title: 'Find the Monkey',
    type: 'word',
    targetWord: 'monkey',
    slowPronunciation: 'Mmmmooonnnkkkeeey',
    instruction: 'Look up in the trees! Say "MONKEY"',
    mascotIntro: 'Who is swinging up there? Say Monkey!',
    mascotSuccess: 'Ooh ooh ah ah! Perfect!',
    emoji: '🐒',
  },
  {
    id: 'lvl-8',
    title: 'Spot the Tiger',
    type: 'word',
    targetWord: 'tiger',
    slowPronunciation: 'Ttttiiiiggggeeeerr',
    instruction: 'Look at those stripes! Say "TIGER"',
    mascotIntro: 'Such a big cat! Practice your T and G in Tiger!',
    mascotSuccess: 'Fierce! Great pronunciation!',
    emoji: '🐅',
  },
  {
    id: 'lvl-9',
    title: 'Talk to the Parrot',
    type: 'word',
    targetWord: 'parrot',
    slowPronunciation: 'Ppppaaarrrrooottt',
    instruction: 'He copies you! Say "PARROT"',
    mascotIntro: 'He will repeat what you say! Say Parrot!',
    mascotSuccess: 'Squawk! Brilliant P sound!',
    emoji: '🦜',
  },
  {
    id: 'lvl-10',
    title: 'Cast a Spell',
    type: 'word',
    targetWord: 'magic',
    slowPronunciation: 'Mmmmaaaagggiiiccc',
    instruction: 'You are a wizard! Say "MAGIC"',
    mascotIntro: 'You reached the end! Cast your final spell... say Magic!',
    mascotSuccess: 'You are a true Speech Wizard! Amazing!',
    emoji: '🪄',
  },
] as const;

export const signLevelSeeds = [
  { id: 'lvl-1', sign: 'one', title: 'The Single Beam', meaning: 'Number One', emoji: '1️⃣', instruction: 'Hold up your Index finger to start the magic!' },
  { id: 'lvl-2', sign: 'peace', title: 'The Peaceful Path', meaning: 'Peace / V', emoji: '✌️', instruction: 'Make a Peace sign with two fingers!' },
  { id: 'lvl-3', sign: 'water', title: 'The Ocean Flow', meaning: 'Water / W', emoji: '💧', instruction: 'Hold up three fingers to summon the water!' },
  { id: 'lvl-4', sign: 'highfive', title: 'The Bright Sun', meaning: 'High Five / Open Hand', emoji: '🖐️', instruction: 'Open your hand wide like a shining sun!' },
  { id: 'lvl-5', sign: 'rock', title: 'The Solid Stone', meaning: 'Rock / Fist', emoji: '✊', instruction: 'Close your hand tight like a heavy stone!' },
  { id: 'lvl-6', sign: 'ice', title: 'The Frost Spark', meaning: 'Ice / Pinky', emoji: '❄️', instruction: 'Hold up just your little Pinky finger!' },
  { id: 'lvl-7', sign: 'love', title: 'The Heart Core', meaning: 'Love / Horns', emoji: '🤟', instruction: 'Index and Pinky up to share the love!' },
  { id: 'lvl-8', sign: 'fox', title: 'The Clever Fox', meaning: 'Fox / 3 Fingers', emoji: '🦊', instruction: 'Middle, Ring, and Pinky up. Index down!' },
  { id: 'lvl-9', sign: 'spider', title: 'The Web Weaver', meaning: 'Spider', emoji: '🕷️', instruction: 'Index, Middle, and Pinky up to spin a web!' },
  { id: 'lvl-10', sign: 'super', title: 'The Lumina Burst', meaning: 'Super / Thumbs Up', emoji: '👍', instruction: 'Give a big Thumbs Up to complete your journey!' },
] as const;

export const planetSeeds = [
  {
    id: 'sun',
    name: 'Sun',
    kind: 'star',
    order: 0,
    color: '#FFD700',
    size: 120,
    orbitRadius: 0,
    orbitSpeed: 0,
    facts: ['The Sun is a star!', 'It gives us light and keeps us warm.'],
    svg: '<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="42" fill="#FFD700" /></svg>',
  },
  {
    id: 'mercury',
    name: 'Mercury',
    kind: 'planet',
    order: 1,
    color: '#A8A8A8',
    size: 30,
    orbitRadius: 100,
    orbitSpeed: 0.02,
    facts: ['Mercury is the smallest planet.', 'It is closest to the Sun!'],
    svg: '<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="36" fill="#A8A8A8" /></svg>',
  },
  {
    id: 'venus',
    name: 'Venus',
    kind: 'planet',
    order: 2,
    color: '#EED053',
    size: 45,
    orbitRadius: 160,
    orbitSpeed: 0.015,
    facts: ['Venus is the hottest planet.', 'It shines very bright in the sky.'],
    svg: '<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="38" fill="#EED053" /></svg>',
  },
  {
    id: 'earth',
    name: 'Earth',
    kind: 'planet',
    order: 3,
    color: '#4B9CD3',
    size: 50,
    orbitRadius: 230,
    orbitSpeed: 0.01,
    facts: ['Earth is our home!', 'It has water, plants, and animals.'],
    svg: '<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="#4B9CD3" /></svg>',
  },
  {
    id: 'mars',
    name: 'Mars',
    kind: 'planet',
    order: 4,
    color: '#E27B58',
    size: 40,
    orbitRadius: 300,
    orbitSpeed: 0.008,
    facts: ['Mars is the red planet.', 'It has the biggest volcano!'],
    svg: '<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="38" fill="#E27B58" /></svg>',
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    kind: 'planet',
    order: 5,
    color: '#D39C7E',
    size: 90,
    orbitRadius: 400,
    orbitSpeed: 0.005,
    facts: ['Jupiter is the biggest planet!', 'It has a giant red spot.'],
    svg: '<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="46" fill="#D39C7E" /></svg>',
  },
  {
    id: 'saturn',
    name: 'Saturn',
    kind: 'planet',
    order: 6,
    color: '#EAD6B8',
    size: 80,
    orbitRadius: 520,
    orbitSpeed: 0.003,
    facts: ['Saturn has beautiful rings!', 'The rings are made of ice and rock.'],
    svg: '<svg viewBox="0 0 100 100"><ellipse cx="50" cy="50" rx="32" ry="18" fill="none" stroke="#C2A170" stroke-width="8" /><circle cx="50" cy="50" r="24" fill="#EAD6B8" /></svg>',
  },
  {
    id: 'uranus',
    name: 'Uranus',
    kind: 'planet',
    order: 7,
    color: '#AEEEEE',
    size: 60,
    orbitRadius: 630,
    orbitSpeed: 0.002,
    facts: ['Uranus spins on its side!', 'It is an ice giant.'],
    svg: '<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="36" fill="#AEEEEE" /></svg>',
  },
  {
    id: 'neptune',
    name: 'Neptune',
    kind: 'planet',
    order: 8,
    color: '#4682B4',
    size: 58,
    orbitRadius: 730,
    orbitSpeed: 0.001,
    facts: ['Neptune is very windy and cold.', 'It is the farthest planet.'],
    svg: '<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="36" fill="#4682B4" /></svg>',
  },
] as const;

export const dashboardSummarySeed = {
  childSlug: 'alex-early-primary',
  childName: 'Alex',
  ageBand: 'Early Primary',
  avatarEmoji: '🧒',
  learningStyle: 'Movement + Visual Cues',
  focusAnimal: 'Rainbow Fox',
  currentStrength: 'Visual Matching',
  currentScore: 9.1,
  confidence: 84,
  completionRate: 92,
  weeklyStars: 48,
  nextMilestone: '60 stars unlocks a surprise badge',
  skillPoints: [
    { label: 'Visual Match', score: 94, color: '#ff78b6' },
    { label: 'Memory', score: 86, color: '#ffd54a' },
    { label: 'Trend', score: 90, color: '#69db96' },
    { label: 'Attention', score: 74, color: '#7dbaff' },
    { label: 'Phonics', score: 68, color: '#a78bfa' },
    { label: 'Counting', score: 79, color: '#fb923c' },
  ],
  progressCards: [
    { label: 'Sessions', value: '3', note: 'completed today', tone: 'from-pink-300 to-pink-500', icon: 'sessions' },
    { label: 'Minutes', value: '25', note: 'focused play', tone: 'from-yellow-200 to-yellow-400', icon: 'minutes' },
    { label: 'Tasks', value: '12', note: 'finished', tone: 'from-lime-300 to-green-400', icon: 'tasks' },
    { label: 'Streak', value: '5', note: 'days active', tone: 'from-sky-300 to-cyan-500', icon: 'streak' },
  ],
  strengths: ['Visual Matching', 'Memory Recall', 'Patient Hand Control', 'Story Picture Clues'],
  weakAreas: ['Number Sequencing', 'Shape Recognition', 'Word Order', 'Fast Equation Recall'],
  sparkMoments: [
    'Stayed calm while fixing a wrong answer',
    'Used hand tracking for 8 smooth drops in a row',
    'Recognized image hints quickly in Guess the Word',
  ],
  recommendedActivities: [
    {
      title: 'Recommended Next Activity',
      body: 'Count-and-Move Game to boost number order with big body movement and color prompts.',
      cta: 'Play Count-and-Move',
      tone: 'from-pink-300 via-rose-300 to-orange-300',
      emoji: '🎲',
      highlights: ['Big body movement', 'Rainbow number prompts', 'Quick win in 5 mins'],
      footer: 'Best for after-school energy',
    },
    {
      title: 'Home Practice Idea',
      body: 'Ask Alex to step on paper numbers in the right order and shout the answer aloud.',
      cta: 'Try At Home',
      tone: 'from-amber-200 via-yellow-200 to-orange-200',
      emoji: '🏠',
      highlights: ['Uses paper cards', 'Parent joins in', 'Boosts sequencing confidence'],
      footer: 'Easy setup with household items',
    },
  ],
  parentActions: [
    'Count steps to the kitchen and match them with number cards.',
    'Hide shapes around the room and do a tiny treasure hunt.',
    'Ask Alex to retell the mascot instructions after each round.',
  ],
  weeklyTrend: [42, 51, 48, 64, 67, 72, 84],
  subjectBreakdown: [
    { label: 'English', value: 36, color: '#fb7185' },
    { label: 'Maths', value: 28, color: '#a78bfa' },
    { label: 'Science', value: 22, color: '#34d399' },
    { label: 'Creative', value: 14, color: '#fbbf24' },
  ],
} as const;

export const notificationSeeds = [
  {
    seedKey: 'alex-win-guess-word',
    childSlug: 'alex-early-primary',
    gameKey: 'guess-word',
    title: 'Big win in Guess the Word',
    detail: 'Alex solved APPLE without help and placed all letters in the correct order.',
    tone: 'success',
    emoji: '🌟',
    createdAt: '2026-04-17T08:58:00.000Z',
  },
  {
    seedKey: 'alex-warning-maths',
    childSlug: 'alex-early-primary',
    gameKey: 'math-equations',
    title: 'Needed help in Maths',
    detail: 'Alex struggled with number sequencing for one round, then corrected it on the second try.',
    tone: 'warning',
    emoji: '🧮',
    createdAt: '2026-04-17T08:52:00.000Z',
  },
  {
    seedKey: 'alex-info-hand-tracking',
    childSlug: 'alex-early-primary',
    gameKey: 'match-letters',
    title: 'Hand tracking got smoother',
    detail: 'Alex completed 8 drag-and-drop actions in a row with steady control.',
    tone: 'info',
    emoji: '🖐️',
    createdAt: '2026-04-17T08:46:00.000Z',
  },
  {
    seedKey: 'alex-confidence-bounced',
    childSlug: 'alex-early-primary',
    gameKey: 'match-letters',
    title: 'Confidence bounced back',
    detail: 'After one wrong match, Alex stayed calm and finished the next task successfully.',
    tone: 'success',
    emoji: '💪',
    createdAt: '2026-04-17T08:39:00.000Z',
  },
] as const;
